export const IMPORTANT_UI_TERMS = [
  'Home',
  'Get Documents',
  'Updates',
  'Book an Appointment',
  'Report an Incident',
  'Past Requests',
  'My Profile',
  'Household and Census',
  'eSerbisyo Chatbot',
  'Service Assistant',
  'Simula',
  'Kumuha ng Dokumento',
  'Mga Update',
  'Mag-book ng Appointment',
  'Mag-ulat ng Insidente',
  'Nakaraang Kahilingan',
  'Aking Profile',
  'Sambahayan at Census',
] as const;
