db-uri = "postgres://postgres:postgres@127.0.0.1:5432/eserbisyo"
db-schemas = "public"
db-anon-role = "postgres"
server-port = 54321
server-host = "127.0.0.1"
jwt-secret = "super-secret-jwt-key-with-at-least-32-characters-long"
